version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - run:
          name: gets the project dependencies
          command: mvn dependency:go-offline
      - run:
          name: test
          command: mvn test
